apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
  - chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      releaseName: vault
      valueFiles:
        - $values/vault/vault-values.yaml
  - repoURL: 'https://github.com/NaimAssoumani/initial-Manifest.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hashicorp